apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: pp-benchmark-large-20
  namespace: default
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: benchmark-large-20
    namespace: default
  placement:
    clusterAffinity:
      clusterNames:
      - edge
      - fog
      - cloud
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
