apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: my-pod-policy
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
      name: nginx-pod
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    spreadConstraints:
      - spreadByField: cluster
        maxGroups: 1
        minGroups: 1
