apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-small-5
  namespace: default
  labels:
    app: small
spec:
  replicas: 5
  selector:
    matchLabels:
      app: small
  template:
    metadata:
      labels:
        app: small
    spec:
      containers:
      - name: app
        image: nginx:stable
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
