apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-large-10
  namespace: default
  labels:
    app: large
spec:
  replicas: 10
  selector:
    matchLabels:
      app: large
  template:
    metadata:
      labels:
        app: large
    spec:
      containers:
      - name: app
        image: nginx:stable
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
