apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-medium-15
  namespace: default
  labels:
    app: medium
spec:
  replicas: 15
  selector:
    matchLabels:
      app: medium
  template:
    metadata:
      labels:
        app: medium
    spec:
      containers:
      - name: app
        image: nginx:stable
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
