apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-power-scheduler
  namespace: karmada-system
  labels:
    app: custom-power-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-power-scheduler
  template:
    metadata:
      labels:
        app: custom-power-scheduler
    spec:
      automountServiceAccountToken: false
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: karmada-scheduler
          image: karmada/karmada-scheduler:power
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10351
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
          command:
            - /bin/karmada-scheduler
            - --kubeconfig=/etc/karmada/config/karmada.config
            - --metrics-bind-address=0.0.0.0:8080
            - --health-probe-bind-address=0.0.0.0:10351
            - --enable-scheduler-estimator=true
            - --leader-elect-resource-name=custom-power-scheduler # Your custom scheduler name
            - --scheduler-name=custom-power-scheduler # Your custom scheduler name
            - --v=4
          volumeMounts:
            - name: karmada-config
              mountPath: /etc/karmada/config
      volumes:
        - name: karmada-config
          secret:
            secretName: karmada-scheduler-config